In [40]:
import pandas as pd
import numpy as np

In [6]:
l=[0,1,3,4]

In [9]:
srs =pd.Series(l,index=[1,2,3,4])

In [10]:
srs

1    0
2    1
3    3
4    4
dtype: int64

In [15]:
srs2=pd.Series(list("abcd"),index=[1,2,3,4])

In [16]:
srs2

1    a
2    b
3    c
4    d
dtype: object

In [34]:
srs3=n=pd.Series([50,56,89],index=["Data science","ANN","network security"])
    

In [35]:
srs3

Data science        50
ANN                 56
network security    89
dtype: int64

In [39]:
srs3[1:2]

ANN    56
dtype: int64

In [24]:
srs3

Data science        50
ANN                 56
network security    89
Name: marks, dtype: int64

In [75]:
arr3=np.arange(16).reshape(1,4,4)

In [83]:
arr4=np.arange(16,dtype="float").reshape(1,4,4)

In [90]:
arr3.ndim

3

In [91]:
arr3

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [92]:
new = np.hsplit(arr3,4)

In [93]:
new

[array([[[ 0.,  1.,  2.,  3.]]]),
 array([[[ 4.,  5.,  6.,  7.]]]),
 array([[[  8.,   9.,  10.,  11.]]]),
 array([[[ 12.,  13.,  14.,  15.]]])]

In [94]:
arr2=np.array([[[1.3,2.8,3.0,4.7],[5.6,6.1,7.9,8.0],[9.7,10.2,11.3,12.7]]])

In [95]:
floor=np.floor(arr4)

In [96]:
floor

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [97]:
seal=np.ceil(arr4)

In [98]:
seal

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.]]])

In [99]:
flat=np.ravel(arr3)

In [100]:
flat

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.])